# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/CJ-MC-Mods/Overloaded/issues" #optional
license="All rights reserved"
[[mods]] #mandatory
modId="overloaded_cb" #mandatory
version="${version}" #mandator
displayName="Overloaded Compressed Blocks" #mandatory
displayURL="https://github.com/CJ-MC-Mods/Overloaded" #optional
logoFile="logo.png" #optional
authors="CJ Miller (cjm721)" #optional
description='''
Allows creation of compressed blocks for any other blocks (this includes other mod's blocks) using a JSON config.
'''
[[dependencies.overloaded_cb]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.overloaded_cb]] #optional
    modId="overloaded" #mandatory
    mandatory=true #mandatory
    versionRange="[0.0.90,)" #mandatory
    ordering="BEFORE"
    side="BOTH"